"""Claude Code integration: hooks that lease skills/agents per prompt.

`gutcheck lease install claude` writes a standalone, stdlib-only hook script and registers it in
~/.claude/settings.json (backed up first):

    SessionStart      -> make sure the lease daemon is running (starts it detached if not)
    UserPromptSubmit  -> ask the daemon what this prompt needs; inject only that as additionalContext

If the daemon is down or slow, the hook prints nothing and exits 0: your prompt is never blocked.
"""
from __future__ import annotations

import datetime as _dt
import json
import os
import shutil
import sys
from typing import Any, Dict, Optional

MARKER = "gutcheck-lease-hook"

HOOK_TEMPLATE = r'''#!/usr/bin/env python3
# gutcheck-lease-hook (generated by `gutcheck lease install`; safe to delete)
import json, os, subprocess, sys, urllib.request

PORT = __PORT__
TIMEOUT = __TIMEOUT__
PYTHON = __PYTHON__
LOG = __LOG__
URL = "http://127.0.0.1:%d" % PORT


def _post(path, obj, timeout):
    req = urllib.request.Request(URL + path, data=json.dumps(obj).encode("utf-8"),
                                 headers={"content-type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode("utf-8"))


def _alive():
    try:
        with urllib.request.urlopen(URL + "/health", timeout=0.3) as r:
            return r.status == 200
    except Exception:
        return False


def session():
    if _alive():
        return
    kw = {"stdout": open(LOG, "a"), "stderr": subprocess.STDOUT, "stdin": subprocess.DEVNULL}
    if os.name == "nt":
        kw["creationflags"] = 0x00000008 | 0x00000200  # DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP
    else:
        kw["start_new_session"] = True
    subprocess.Popen([PYTHON, "-m", "gutcheck", "lease", "serve"], **kw)


def prompt():
    try:
        data = json.loads(sys.stdin.read() or "{}")
    except Exception:
        return
    text = data.get("prompt") or ""
    if len(text.strip()) < 3:
        return
    try:
        res = _post("/lease", {"prompt": text}, TIMEOUT)
    except Exception:
        if not _alive():
            session()  # start it for the next prompt; never block this one
        return
    ctx = res.get("context") or ""
    if ctx:
        print(json.dumps({"hookSpecificOutput": {"hookEventName": "UserPromptSubmit", "additionalContext": ctx}}))


if __name__ == "__main__":
    try:
        {"session": session, "prompt": prompt}.get(sys.argv[1] if len(sys.argv) > 1 else "prompt", prompt)()
    except Exception:
        pass
    sys.exit(0)
'''


def write_hook_script(port: int, timeout_ms: int, python: Optional[str] = None, dest: Optional[str] = None) -> str:
    from ..runtime.openvino_backend import cache_root

    dest = dest or os.path.join(cache_root(), "hooks", "gutcheck_lease_hook.py")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    body = (HOOK_TEMPLATE.replace("__PORT__", str(int(port)))
            .replace("__TIMEOUT__", repr(timeout_ms / 1000.0))
            .replace("__PYTHON__", repr(python or sys.executable))
            .replace("__LOG__", repr(os.path.join(cache_root(), "lease.log"))))
    with open(dest, "w", encoding="utf-8") as f:
        f.write(body)
    return dest


def _cmd(script: str, mode: str) -> str:
    py = sys.executable.replace("\\", "/")
    return '"%s" "%s" %s' % (py, script.replace("\\", "/"), mode)


def install(settings_path: Optional[str] = None, dry_run: bool = False) -> Dict[str, Any]:
    from .config import load_config

    cfg = load_config()
    settings_path = os.path.expanduser(settings_path or "~/.claude/settings.json")
    script = write_hook_script(cfg["port"], cfg["timeout_ms"]) if not dry_run else "<hook script>"
    settings: Dict[str, Any] = {}
    if os.path.exists(settings_path):
        with open(settings_path, encoding="utf-8") as f:
            settings = json.load(f)
    new = json.loads(json.dumps(settings))
    hooks = new.setdefault("hooks", {})
    for event, mode, timeout in (("SessionStart", "session", 10), ("UserPromptSubmit", "prompt", 5)):
        groups = [g for g in hooks.get(event, []) if MARKER not in json.dumps(g) and "gutcheck_lease_hook" not in json.dumps(g)]
        groups.append({"hooks": [{"type": "command", "command": _cmd(script, mode), "timeout": timeout}]})
        hooks[event] = groups
    if dry_run:
        return {"settings": settings_path, "would_write": new}
    if os.path.exists(settings_path):
        backup = settings_path + ".gutcheck-backup-" + _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
        shutil.copyfile(settings_path, backup)
    else:
        backup = None
        os.makedirs(os.path.dirname(settings_path), exist_ok=True)
    with open(settings_path, "w", encoding="utf-8") as f:
        json.dump(new, f, indent=2)
    return {"settings": settings_path, "backup": backup, "hook": script}


def uninstall(settings_path: Optional[str] = None) -> Dict[str, Any]:
    settings_path = os.path.expanduser(settings_path or "~/.claude/settings.json")
    if not os.path.exists(settings_path):
        return {"settings": settings_path, "removed": 0}
    with open(settings_path, encoding="utf-8") as f:
        settings = json.load(f)
    removed = 0
    for event, groups in list(settings.get("hooks", {}).items()):
        keep = [g for g in groups if "gutcheck_lease_hook" not in json.dumps(g)]
        removed += len(groups) - len(keep)
        if keep:
            settings["hooks"][event] = keep
        else:
            del settings["hooks"][event]
    if removed:
        shutil.copyfile(settings_path, settings_path + ".gutcheck-backup-" + _dt.datetime.now().strftime("%Y%m%d-%H%M%S"))
        with open(settings_path, "w", encoding="utf-8") as f:
            json.dump(settings, f, indent=2)
    return {"settings": settings_path, "removed": removed}
